### PR TITLE
provide a way to convert MappingType to Model without retrieving data from Git

### PR DESCRIPTION
**Pull request by Rizziepit**

### CODE REVIEW

**Comment by Rizziepit** [comment]
@smn @miltontony ready for review

**Comment by Rizziepit** [comment]
@smn @miltontony ready for review for real this time.

I found some interesting behaviour in elasticutils w.r.t. datetime conversion [here](https://github.com/mozilla/elasticutils/blob/b751188b6685d1c6cba57e7409782fb84d1b7e7a/elasticutils/__init__.py#L430).

Elasticutils tries to convert anything that looks datetime-ish to a `datetime` object. IMO, it's best to disable that behaviour. Reasons:

1. It doesn't convert consistently, e.g. timezone-aware dates are left as strings.
2. It doesn't take the mapping type into account. So we can't ensure that a `TextField` value will have a `string` type - this is the issue at the moment in `unicore.content` where timestamps are stored as strings.
3. `Model` fields can do a better job at conversion.

**Comment by miltontony** [comment]
:+1:  from me.
@smn please have a second look since this is your domain

**Comment by smn** [comment]
Is there a way we can test the `to_python` stuff in `S(SBase)` ?

**Comment by smn** [comment]
:+1: regardless of my previous comment.

**Comment by Rizziepit** [comment]
I wrote a test to check that the custom S object is returned, and a basic test to check the equivalence of the old and new `to_python` methods.

Side note: the docs mention overriding the `S.to_python` method. So that part of the API probably won't change soon.

**Comment by smn** [comment]
:+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake: :+1: :cake:

**Pull request merged**
